import sys
import logging

quartos = {}
try:
    for line in open("")
except FileNotFoundError:
    logging.error("Arquivo n√£o existe")
    sys.exit(1)
